import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";
import { api } from "~/utils/api";

export default function Home() {

  const session = useSession()

  console.log(session)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>Home</div>
        <Link href={"/auth/login"}>Login</Link>
        <Button onClick={() => void signOut()}>Sign Out</Button>
      </main>
    </>
  );
}
